name: CI

on: [push]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php: ['7.3', '7.4', '8.0']
        woo: ['latest']
    name: PHP ${{ matrix.php }} test for Woo ${{ matrix.woo }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          ini-values: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
          coverage: xdebug #optional, setup coverage driver

      - name: Composer install
        run: composer install --no-interaction

      - name: Install compatibility-with-php8-to-phpunit-7
        if: ${{ matrix.php == '8.0' }}
        run: |
          composer config repositories.0 '{"type":"package","package":{"name":"phpunit/phpunit","version":"7.5.99","dist":{"url":"https://github.com/woocommerce/phpunit/archive/add-compatibility-with-php8-to-phpunit-7.zip","type":"zip"},"require":{"php":"^7.1","ext-dom":"*","ext-json":"*","ext-libxml":"*","ext-mbstring":"*","ext-xml":"*","doctrine/instantiator":"^1.1","myclabs/deep-copy":"^1.7","phar-io/manifest":"^1.0.2","phar-io/version":"^2.0","phpspec/prophecy":"^1.7","phpunit/php-code-coverage":"^6.0.7","phpunit/php-file-iterator":"^2.0.1","phpunit/php-text-template":"^1.2.1","phpunit/php-timer":"^2.1","sebastian/comparator":"^3.0","sebastian/diff":"^3.0","sebastian/environment":"^4.0","sebastian/exporter":"^3.1","sebastian/global-state":"^2.0","sebastian/object-enumerator":"^3.0.3","sebastian/resource-operations":"^2.0","sebastian/version":"^2.0.1"},"bin":["phpunit"],"autoload":{"classmap":["src/"]}}}'
          composer require --dev --update-with-all-dependencies phpunit/phpunit:7.5.999

      - name: Install WP Tests
        run: bash tests/bin/install.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports['3306'] }} latest ${{ matrix.woo }} true

      - name: phpunit tests
        run: ./vendor/bin/phpunit
